/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: sanity/extract.json
export type WaitlistEntry = {
  _id: string;
  _type: "waitlistEntry";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  firstName?: string;
  lastName?: string;
  email?: string;
  phone?: string;
  company?: string;
  message?: string;
  submittedAt?: string;
};

export type WaitlistPage = {
  _id: string;
  _type: "waitlistPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  eyebrow?: string;
  heading?: string;
  intro?: string;
  form?: {
    firstNameLabel?: string;
    lastNameLabel?: string;
    emailLabel?: string;
    phoneLabel?: string;
    companyLabel?: string;
    messageLabel?: string;
    optionalText?: string;
    submitLabel?: string;
    submittingLabel?: string;
    successHeading?: string;
    successMessage?: string;
    requiredError?: string;
    emailError?: string;
    genericError?: string;
  };
};

export type ResultsPage = {
  _id: string;
  _type: "resultsPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  year?: number;
  title?: string;
  intro?: string;
};

export type PlayerBiosPage = {
  _id: string;
  _type: "playerBiosPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  year?: number;
  title?: string;
  eyebrow?: string;
  heading?: string;
  teams?: Array<{
    name?: string;
    players?: Array<{
      name?: string;
      photo?: ImageWithAlt;
      role?: string;
      bio?: Array<{
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "normal";
        listItem?: never;
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }>;
      _type: "player";
      _key: string;
    }>;
    _type: "team";
    _key: string;
  }>;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type ImageWithAlt = {
  _type: "imageWithAlt";
  asset?: SanityImageAssetReference;
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt?: string;
};

export type SwagPage = {
  _id: string;
  _type: "swagPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  year?: number;
  title?: string;
  eyebrow?: string;
  heading?: string;
  image?: ImageWithAlt;
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: "bullet";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type EventPhotosPage = {
  _id: string;
  _type: "eventPhotosPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  year?: number;
  title?: string;
  eyebrow?: string;
  heading?: string;
  photos?: Array<
    {
      _key: string;
    } & ImageWithAlt
  >;
};

export type SanityFileAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
};

export type CoursePage = {
  _id: string;
  _type: "coursePage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  year?: number;
  title?: string;
  hero?: {
    eyebrow?: string;
    heading?: string;
    video?: {
      asset?: SanityFileAssetReference;
      media?: unknown;
      _type: "file";
    };
    poster?: ImageWithAlt;
  };
  about?: {
    heading?: string;
    body?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal";
      listItem?: never;
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }>;
  };
  details?: {
    heading?: string;
    items?: Array<string>;
  };
  photos?: {
    heading?: string;
    images?: Array<
      {
        _key: string;
      } & ImageWithAlt
    >;
  };
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  logo?: ImageWithAlt;
  logoText?: {
    prefix?: string;
    highlight?: string;
    suffix?: string;
  };
  menuLabel?: string;
  navMenus?: Array<{
    label?: string;
    links?: Array<{
      label?: string;
      href?: string;
      _type: "navLink";
      _key: string;
    }>;
    emptyText?: string;
    _type: "navMenu";
    _key: string;
  }>;
  footerText?: string;
  siteTitle?: string;
  siteDescription?: string;
};

export type HomePage = {
  _id: string;
  _type: "homePage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  hero?: {
    heading?: string;
    image?: ImageWithAlt;
  };
  about?: {
    heading?: string;
    body?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal";
      listItem?: never;
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }>;
    images?: Array<
      {
        _key: string;
      } & ImageWithAlt
    >;
  };
  faq?: {
    heading?: string;
    items?: Array<{
      question?: string;
      answer?: string;
      _type: "faqItem";
      _key: string;
    }>;
  };
  testimonials?: {
    heading?: string;
    items?: Array<{
      quote?: string;
      name?: string;
      role?: string;
      photo?: ImageWithAlt;
      _type: "testimonial";
      _key: string;
    }>;
  };
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type AllSanitySchemaTypes =
  | WaitlistEntry
  | WaitlistPage
  | ResultsPage
  | PlayerBiosPage
  | SanityImageAssetReference
  | ImageWithAlt
  | SwagPage
  | EventPhotosPage
  | SanityFileAssetReference
  | CoursePage
  | SiteSettings
  | HomePage
  | SanityImageCrop
  | SanityImageHotspot
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint
  | Slug;

// Source: sanity/lib/queries.ts
// Variable: siteSettingsQuery
// Query: *[_type == "siteSettings"][0]{  siteTitle,  siteDescription,  logo{asset, hotspot, crop, alt},  logoText{prefix, highlight, suffix},  menuLabel,  navMenus[]{_key, label, emptyText, links[]{_key, label, href}},  footerText}
export type SiteSettingsQueryResult = {
  siteTitle: string | null;
  siteDescription: string | null;
  logo: {
    asset: SanityImageAssetReference | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
    alt: string | null;
  } | null;
  logoText: {
    prefix: string | null;
    highlight: string | null;
    suffix: string | null;
  } | null;
  menuLabel: string | null;
  navMenus: Array<{
    _key: string;
    label: string | null;
    emptyText: string | null;
    links: Array<{
      _key: string;
      label: string | null;
      href: string | null;
    }> | null;
  }> | null;
  footerText: string | null;
} | null;

// Source: sanity/lib/queries.ts
// Variable: homePageQuery
// Query: *[_type == "homePage"][0]{  hero{heading, image{asset, hotspot, crop, alt}},  about{heading, body, images[]{_key, asset, hotspot, crop, alt}},  faq{heading, items[]{_key, question, answer}},  testimonials{heading, items[]{_key, quote, name, role, photo{asset, hotspot, crop, alt}}}}
export type HomePageQueryResult = {
  hero: {
    heading: string | null;
    image: {
      asset: SanityImageAssetReference | null;
      hotspot: SanityImageHotspot | null;
      crop: SanityImageCrop | null;
      alt: string | null;
    } | null;
  } | null;
  about: {
    heading: string | null;
    body: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal";
      listItem?: never;
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }> | null;
    images: Array<{
      _key: string;
      asset: SanityImageAssetReference | null;
      hotspot: SanityImageHotspot | null;
      crop: SanityImageCrop | null;
      alt: string | null;
    }> | null;
  } | null;
  faq: {
    heading: string | null;
    items: Array<{
      _key: string;
      question: string | null;
      answer: string | null;
    }> | null;
  } | null;
  testimonials: {
    heading: string | null;
    items: Array<{
      _key: string;
      quote: string | null;
      name: string | null;
      role: string | null;
      photo: {
        asset: SanityImageAssetReference | null;
        hotspot: SanityImageHotspot | null;
        crop: SanityImageCrop | null;
        alt: string | null;
      } | null;
    }> | null;
  } | null;
} | null;

// Source: sanity/lib/queries.ts
// Variable: seasonPageQuery
// Query: *[_type == $type && year == $year][0]{  year,  title,  intro}
export type SeasonPageQueryResult =
  | {
      year: null;
      title: null;
      intro: null;
    }
  | {
      year: null;
      title: string | null;
      intro: null;
    }
  | {
      year: number | null;
      title: string | null;
      intro: null;
    }
  | {
      year: null;
      title: string | null;
      intro: string | null;
    }
  | {
      year: number | null;
      title: string | null;
      intro: string | null;
    }
  | null;

// Source: sanity/lib/queries.ts
// Variable: coursePageQuery
// Query: *[_type == "coursePage" && year == $year][0]{  year,  title,  hero{eyebrow, heading, "videoUrl": video.asset->url, "videoType": video.asset->mimeType, poster{asset, hotspot, crop, alt}},  about{heading, body},  details{heading, items},  photos{heading, images[]{_key, asset, hotspot, crop, alt}}}
export type CoursePageQueryResult = {
  year: number | null;
  title: string | null;
  hero: {
    eyebrow: string | null;
    heading: string | null;
    videoUrl: string | null;
    videoType: string | null;
    poster: {
      asset: SanityImageAssetReference | null;
      hotspot: SanityImageHotspot | null;
      crop: SanityImageCrop | null;
      alt: string | null;
    } | null;
  } | null;
  about: {
    heading: string | null;
    body: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal";
      listItem?: never;
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }> | null;
  } | null;
  details: {
    heading: string | null;
    items: Array<string> | null;
  } | null;
  photos: {
    heading: string | null;
    images: Array<{
      _key: string;
      asset: SanityImageAssetReference | null;
      hotspot: SanityImageHotspot | null;
      crop: SanityImageCrop | null;
      alt: string | null;
    }> | null;
  } | null;
} | null;

// Source: sanity/lib/queries.ts
// Variable: eventPhotosPageQuery
// Query: *[_type == "eventPhotosPage" && year == $year][0]{  year,  title,  eyebrow,  heading,  photos[]{_key, asset, hotspot, crop, alt}}
export type EventPhotosPageQueryResult = {
  year: number | null;
  title: string | null;
  eyebrow: string | null;
  heading: string | null;
  photos: Array<{
    _key: string;
    asset: SanityImageAssetReference | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
    alt: string | null;
  }> | null;
} | null;

// Source: sanity/lib/queries.ts
// Variable: swagPageQuery
// Query: *[_type == "swagPage" && year == $year][0]{  year,  title,  eyebrow,  heading,  image{asset, hotspot, crop, alt},  body}
export type SwagPageQueryResult = {
  year: number | null;
  title: string | null;
  eyebrow: string | null;
  heading: string | null;
  image: {
    asset: SanityImageAssetReference | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
    alt: string | null;
  } | null;
  body: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: "bullet";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
} | null;

// Source: sanity/lib/queries.ts
// Variable: playerBiosPageQuery
// Query: *[_type == "playerBiosPage" && year == $year][0]{  year,  title,  eyebrow,  heading,  teams[]{_key, name, players[]{_key, name, role, bio, photo{asset, hotspot, crop, alt}}}}
export type PlayerBiosPageQueryResult = {
  year: number | null;
  title: string | null;
  eyebrow: string | null;
  heading: string | null;
  teams: Array<{
    _key: string;
    name: string | null;
    players: Array<{
      _key: string;
      name: string | null;
      role: string | null;
      bio: Array<{
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "normal";
        listItem?: never;
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }> | null;
      photo: {
        asset: SanityImageAssetReference | null;
        hotspot: SanityImageHotspot | null;
        crop: SanityImageCrop | null;
        alt: string | null;
      } | null;
    }> | null;
  }> | null;
} | null;

// Source: sanity/lib/queries.ts
// Variable: waitlistPageQuery
// Query: *[_type == "waitlistPage"][0]{  title,  eyebrow,  heading,  intro,  form}
export type WaitlistPageQueryResult = {
  title: string | null;
  eyebrow: string | null;
  heading: string | null;
  intro: string | null;
  form: {
    firstNameLabel?: string;
    lastNameLabel?: string;
    emailLabel?: string;
    phoneLabel?: string;
    companyLabel?: string;
    messageLabel?: string;
    optionalText?: string;
    submitLabel?: string;
    submittingLabel?: string;
    successHeading?: string;
    successMessage?: string;
    requiredError?: string;
    emailError?: string;
    genericError?: string;
  } | null;
} | null;

// Query TypeMap
declare global {
  interface SanityQueries {
    '*[_type == "siteSettings"][0]{\n  siteTitle,\n  siteDescription,\n  logo{asset, hotspot, crop, alt},\n  logoText{prefix, highlight, suffix},\n  menuLabel,\n  navMenus[]{_key, label, emptyText, links[]{_key, label, href}},\n  footerText\n}': SiteSettingsQueryResult;
    '*[_type == "homePage"][0]{\n  hero{heading, image{asset, hotspot, crop, alt}},\n  about{heading, body, images[]{_key, asset, hotspot, crop, alt}},\n  faq{heading, items[]{_key, question, answer}},\n  testimonials{heading, items[]{_key, quote, name, role, photo{asset, hotspot, crop, alt}}}\n}': HomePageQueryResult;
    "*[_type == $type && year == $year][0]{\n  year,\n  title,\n  intro\n}": SeasonPageQueryResult;
    '*[_type == "coursePage" && year == $year][0]{\n  year,\n  title,\n  hero{eyebrow, heading, "videoUrl": video.asset->url, "videoType": video.asset->mimeType, poster{asset, hotspot, crop, alt}},\n  about{heading, body},\n  details{heading, items},\n  photos{heading, images[]{_key, asset, hotspot, crop, alt}}\n}': CoursePageQueryResult;
    '*[_type == "eventPhotosPage" && year == $year][0]{\n  year,\n  title,\n  eyebrow,\n  heading,\n  photos[]{_key, asset, hotspot, crop, alt}\n}': EventPhotosPageQueryResult;
    '*[_type == "swagPage" && year == $year][0]{\n  year,\n  title,\n  eyebrow,\n  heading,\n  image{asset, hotspot, crop, alt},\n  body\n}': SwagPageQueryResult;
    '*[_type == "playerBiosPage" && year == $year][0]{\n  year,\n  title,\n  eyebrow,\n  heading,\n  teams[]{_key, name, players[]{_key, name, role, bio, photo{asset, hotspot, crop, alt}}}\n}': PlayerBiosPageQueryResult;
    '*[_type == "waitlistPage"][0]{\n  title,\n  eyebrow,\n  heading,\n  intro,\n  form\n}': WaitlistPageQueryResult;
  }
}
// Lets @sanity/client releases that predate the global registry read it too
declare module "@sanity/client" {
  interface SanityQueries extends globalThis.SanityQueries {}
}
